# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: Add labels

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
    - name: Add labels
      uses: actions/label@v2
      if: ${{ contains(toJson(github.event.pull_request.title), 'bug') }}
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        labels: "bug"
    - name: Add labels
      uses: actions/label@v2
      if: ${{ contains(toJson(github.event.pull_request.title), 'enhancement') }}
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        labels: "enhancement"
    - name: Add labels
      uses: actions/label@v2
      if: ${{ contains(toJson(github.event.pull_request.title), 'question') }}
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        labels: "question"
    - name: Add labels
      uses: actions/label@v2
      if: ${{ contains(toJson(github.event.pull_request.title), 'website') }}
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        labels: "area/website"
    - name: Add labels
      uses: actions/label@v2
      if: ${{ contains(toJson(github.event.pull_request.title), 'doc') }}
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        labels: "area/doc"

